apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270calebservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270calebservice
  template:
    metadata:
      name: cit270calebservice
      labels:
        app: cit270calebservice
    spec:
      containers:
        - name: cit270calebservice
        image: mythic-producer-379820/caleb-api
        volumeMounts:
          - name: ssl
            mountPath: "/etc/letsencrypt/live/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
        - name: ssl
        secret:
          secretName: calebcerts